language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    global:
        # GH_TOKEN define in repository settings on travis-ci.org
        - GH_REPO: github.com/locomotivemtl/charcoal-cache.git
        - GH_PAGES: locomotivemtl.github.io/charcoal-cache

matrix:
    allow_failures:
        - php: nightly

before_install:
    - composer self-update --quiet

install:
    - composer install --no-interaction --no-suggest
    - mkdir -p build/logs/

script:
    - composer phplint
    - composer phpcs
    #- composer phpunit -- --coverage-clover "build/logs/clover.xml"

after_script:
    #- php vendor/bin/php-coveralls -v
    #- bash build/travis/phpdoc_ghpages.sh
    #- bash build/travis/apigen_ghpages.sh

notifications:
    slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
    email: charcoal@locomotive.ca